language: node_js
node_js:
  - 4
  - 6
  - 7
  - 8
cache:
  yarn: true
  directories:
    - node_modules
    - packages/create-landing-page/node_modules
    - packages/landing-scripts/node_modules

install:
  - yarn install

script:
  - tests/e2e.sh
