language: node_js
node_js:
  - 8
cache:
  yarn: true
  directories:
    - node_modules
    - packages/create-landing-page/node_modules
    - packages/landing-scripts/node_modules

install:
  - yarn install

before_install:
  - chmod +x tests/e2e.sh

script:
  - tests/e2e.sh
